version: '3'
services:
  bd: 
    image: mysql:5.7
    container_name: srv_bd
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      #MYSQL_DATABASE: teste
      #MYSQL_USER: adm
      #MYSQL_PASSWORD: 123456
      MYSQL_PORT: 3306
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
    restart: always

  web:
    image: nginx:1.12
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./web.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: php
    environment:
      - PHP_FPM_INSTALL_MYSQLI=true
    volumes:
        - ./code:/code
        - ./php/php.ini:/usr/local/etc/php/php.ini
        - ./php/cacert.pem:/etc/ssl/demoCA/cacert.pem
    links:
      - bd
    