version: '3'
services:
  bd: 
    image: mysql:5.7
    container_name: srv_bd
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      #MYSQL_DATABASE: teste
      #MYSQL_USER: adm
      #MYSQL_PASSWORD: 123456
      MYSQL_PORT: 3306
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
    restart: always
  web:
    image: nginx:1.12
    ports:
      - "8080:80"
    volumes:
      - ./code/frontend:/code
      - ./web.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - nodejs
    depends_on:
      - php
      - nodejs

  php:
    build: php
    environment:
      - PHP_FPM_INSTALL_MYSQLI=true
    volumes:
      - ./code/apiphp:/code
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/cacert.pem:/etc/ssl/demoCA/cacert.pem
    ports:
      - 9000:9000
    links:
      - bd
    depends_on:
      - bd

  nodejs:
    image: node:8.9
    volumes:
      - ./code/apinode:/code
    ports:
      - 3000:3000
    command: bash -c "cd /code && npm i && node app"
    links:
      - bd
    depends_on:
      - bd
  
  python:
    image: python:3.6
    volumes:
      # Aplicação
      - ./code/apipython:/code
    working_dir: /code
    ports:
      - 8000:8000
    command: bash ./app.sh
    links:
      - bd
    depends_on:
      - bd

